# Write a function nearly equal to test whether two strings are nearly equal. Two strings a andb are nearly equal when a can be generated by a single mutation on.
def str_equal(str1, str2):
    if abs(len(str1) - len(str2)) > 1:
        return False

    i = j = 0
    count = 0

    while i < len(str1) and j < len(str2):
        if str1[i] != str2[j]:
            count += 1
            if count > 1:
                return False
            if len(str1) == len(str2):
                i += 1
                j += 1
            elif len(str1) > len(str2):
                i += 1
            else:
                j += 1
        else:
            i += 1
            j += 1

   

    return count <= 1

str1 = input("Enter first string: ")
str2 = input("Enter second string: ")

if str_equal(str1, str2):
    print("Strings are nearly equal.")
else:
    print("Strings are not equal.")
